### ISSUE TITLE
how to get AppleWebKit ?

### ISSUE THREAD

**Issue by liuxiaojun** [selwin/python-user-agents#20]
for example
Mozilla/5.0 (iPhone; CPU iPhone OS 5_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B179 Safari/7534.48.3

how to get AppleWebKit ?

**Comment by selwin** [comment]
If what you want is to know is whether a user agent is webkit based, you can just search for the string "webkit" in the user agent string (though there's no guarantee that all webkit based browsers include that).
