### ISSUE TITLE
expecting mobile

### ISSUE THREAD

**Issue by az0** [selwin/python-user-agents#22]
user agents that I think should be classified as mobile but they are not

https://gist.github.com/az0/1622a7bf531b71a6e5e9

**Comment by selwin** [comment]
You're right, will work on this on Monday

**Comment by az0** [comment]
I updated the Gist with 157 BlackBerry user agent strings

**Comment by selwin** [comment]
Most of this should be fixed here: https://github.com/selwin/python-user-agents/commit/89ca040f9afb794b9006bdf3ffbc1bdd160b55b5

As for the BlackBerry ones, you should install the latest version of `ua-parser` with `pip install -U ua-parser`

**Comment by az0** [comment]
Thank you. I will update and check again
