### ISSUE TITLE
Googlebot mobile detection does not work for the smartphone googlebot

### ISSUE THREAD

**Issue by ascendingone** [selwin/python-user-agents#24]
The smartphone googlebot user agent listed here does not get detected as mobile:
Mozilla/5.0 (iPhone; CPU iPhone OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5376e Safari/8536.25 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

This is referenced from https://developers.google.com/webmasters/mobile-sites/references/googlebot

The other feature phone googlebots do get detected as mobile.

It appears that Mobile Safari is not being picked up as the browser by the underlying ua_parser library so the check for 'Mobile' in browser does not work. I'm not sure if the fix for this is altering the ua_parser code or the code here.

**Comment by selwin** [comment]
Fixed in https://github.com/selwin/python-user-agents/commit/ec2a0d3154b2bb4bf9a1dc852c802b317905ce63
