### ISSUE TITLE
Failed to detect windows 10 version

### ISSUE THREAD

**Issue by heynemann** [selwin/python-user-agents#34]
Thanks for a great library man!

**Comment by selwin** [comment]
Could you please paste the user agent string here?

**Comment by heynemann** [comment]
Sure, silly me... Sorry for it:

User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by heynemann** [comment]
I'm using chrome on windows 10.

**Comment by selwin** [comment]
I just released `ua-parser` 0.4, this should now work if you update `ua-parser`.
