### ISSUE TITLE
Issue with parsing Googlebot user agents

### ISSUE THREAD

**Issue by akkumar** [selwin/python-user-agents#41]
user-agent-string: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) 

Traceback (most recent call last):
    user_agent = parse(ua_string)
  File "/../lib/python2.7/site-packages/user_agents/parsers.py", line 226, in parse
    return UserAgent(user_agent_string)
  File "/.../local/lib/python2.7/site-packages/user_agents/parsers.py", line 129, in __init__
    self.device = parse_device(**ua_dict['device'])
TypeError: parse_device() takes exactly 3 arguments (1 given)

version: 1.0.1 

This was returning without any issues in 0.3.2 earlier though. Problem occuring only since 1.0.1 .  regression ? 

More user-agents exhibiting this behavior:

Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko; googleweblight) Chrome/38.0.1025.166 Mobile Safari/535.19 

 Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

FYI

**Comment by wsnooknlz** [comment]
Do you have an old version of ua-parser installed? I was able to resolve a similar issue by specifying `ua-parser=0.5.1` in my requirements.

Here's what `pip freeze` looked like for me in a cleanly rebuilt virtual environment after upgrading to user-agents 1.0.1:

```
...
ua-parser==0.5.1
user-agents==1.0.1
...
```

and here's what it looked like in my virtual environment where I'd just done a `pip instal -r ...` after upgrading user-agents

```
...
ua-parser==0.3.6
user-agents==1.0.1
...
```

After running `pip -r ...` again with ua-parser 0.5.1, my tests started passing again (no more errors about `parse_device() `)

**Comment by naoyeye** [comment]
@wsnooknlz thanks!  
`sudo pip install ua-parser==0.5.1` 
worked for me. :P
