### ISSUE TITLE
Bump ua-parser pypi package to 0.5.0.

### ISSUE THREAD

**Issue by jdalton** [selwin/python-user-agents#45]
Pinging [again](https://github.com/selwin/python-user-agents/commit/f1d024c342a4dbdbe9c6bca3a2fd7ee9fb890c98#commitcomment-13225151).

@selwin I noticed you manage the package for [ua-parser](https://pypi.python.org/pypi/ua-parser).
It's been bumped bumped to consume uap-core 0.5.0.

**Comment by selwin** [comment]
0.5 is now release on PyPI. Next time, please open an issue at `ua-parser` instead of this repository. Thanks
