### ISSUE TITLE
Microsoft Edge is not detected

### ISSUE THREAD

**Issue by adamlwgriffiths** [selwin/python-user-agents#65]
`Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136`

```
>>> parse( 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136' ).device
Device(family='Other', brand=None, model=None)
```

https://stackoverflow.com/questions/30591706/what-is-the-user-agent-string-name-for-microsoft-edge

MS details for user-agent string in Edge
https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

**Comment by fabiant7t** [comment]
```
>>> parse( 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10136' ).browser
Browser(family='Edge', version=(12, 10136), version_string='12.10136')
```
I guess you might want to have a look at the property `browser` instead of `device`?!

**Comment by adamlwgriffiths** [comment]
That might help =P
