### ISSUE TITLE
is_mobile error

### ISSUE THREAD

**Issue by zivsu** [selwin/python-user-agents#82]
**user agent:**
Mozilla/5.0 (Linux; Android 6.0.1; Redmi Note 4X Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043409 Safari/537.36 MicroMessenger/6.5.13.1100 NetType/WIFI Language/zh_CN

**is_mobile return false(should be true)**

**Comment by baby5** [comment]
this pkg does not support Chinese mobile brand
