### ISSUE TITLE
Browser Family error?

### ISSUE THREAD

**Issue by sursu** [selwin/python-user-agents#86]
Take the following User Agent instance:
`'Mozilla/5.0 (Linux; Android 5.0.2; SM-T535 Build/LRX22G; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Safari/537.36 [FB_IAB/FB4A;FBAV/77.0.0.20.66;]'`

Place that in a variable `ua`, then:

`parse(ua).browser.family`

says that the browser family is 'Facebook'. 

I have never heard of such a browser family.

Is this behavior correct?

**Comment by Bentipe** [comment]
Yes it is, as in app browser on facebook gets that
